---
- hosts: localhost
  vars:
    IDENTIFIER: '{{ identifier }}'
  remote_user: root
  tasks:
  - script: "/home/kylin/chef12/settings/dockerchefclient/runchefclientdocker.sh {{ IDENTIFIER }} || :"
    ignore_errors: yes
    changed_when: False
# - name: Run expect to wait for a successful PXE boot via out-of-band CIMC
#  shell: /home/kylin/chef12/settings/dockerchefclient/runchefclientdocker.sh {{ IDENTIFIER }}
#
#  - name: execute scripts by identifier    
#    yum: name=httpd state=latest
#  - name: write the apache config file
#    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
#    notify:
#    - restart apache
#  - name: ensure apache is running (and enable it at boot)
#    service: name=httpd state=started enabled=yes
#  handlers:
#    - name: restart apache
#      service: name=httpd state=restarted
