include_recipe "redis::_group"
include_recipe "redis::_user"
include_recipe "redis::_server_install_from_source"
include_recipe "redis::_server_config"
include_recipe "redis::_server_init"
include_recipe "redis::_server_service"